COLORS = {
    "root_bg": "#FAF6F1",
    "left_bg": "#2C1A0E",
    "left_btn_active": "#C8873A",
    "left_btn_inactive": "#3D2612",
    "left_text": "#F5E6D3",
    "left_text_dim": "#A0785A",
    "accent": "#C8873A",
    "accent_light": "#F5E6D3",
    "danger": "#E05A4E",
    "danger_light": "#FDECEA",
    "success": "#4CAF50",
    "white": "#FFFFFF",
    "card_bg": "#FFFFFF",
    "card_border": "#DDD0C0",
    "card_hover": "#F0E0CC",
    "divider": "#EDE0D4",
    "text_primary": "#1A1A1A",
    "text_secondary": "#7A6A5A",
    "row_alt": "#FBF5EE",
    "title_bar": "#2C1A0E",
    "size_btn_active": "#C8873A",
    "size_btn_inactive": "#F5F0EA",
    "size_border": "#C8873A",
}

FONTS = {
    "shop_name": ("Helvetica", 13, "bold"),
    "tagline": ("Helvetica", 10),
    "nav_btn": ("Helvetica", 11, "bold"),
    "section_hdr": ("Helvetica", 13, "bold"),
    "menu_name": ("Helvetica", 11, "bold"),
    "menu_price": ("Helvetica", 10),
    "menu_sizes": ("Helvetica", 9),
    "size_btn": ("Helvetica", 11, "bold"),
    "size_price": ("Helvetica", 10),
    "order_item": ("Helvetica", 11, "bold"),
    "order_sub": ("Helvetica", 10),
    "summary_lbl": ("Helvetica", 11),
    "total_lbl": ("Helvetica", 16, "bold"),
    "action_btn": ("Helvetica", 11),
    "place_btn": ("Helvetica", 13, "bold"),
    "receipt": ("Courier", 10),
    "small": ("Helvetica", 9),
    "input": ("Helvetica", 11),
}

APP = {
    "name": "Kofee Manila",
    "tagline": "POS System",
    "tax_rate": 0.12,
    "window_w": 1280,
    "window_h": 780,
    "db_file": "coffee_pos.db",
    "sizes": ["Small", "Medium", "Large"],
}
